name: George
favicon: null
layout_spectrum: 0.50591
typography_spectrum: 0.38812
title: George
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#101010'
    - '#696969'
    - '#cecece'
    - '#c7b300'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
