name: George
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38812
title: George
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171717'
    - '#746b59'
    - '#e5e5e5'
    - '#6c2c2a'
    - '#f20000'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
